[build]
  command = "npm install && npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-forms"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  functions = "netlify/functions"

